image: docker:19.03.0

stages:
  - build
  - lint
  - test
  - docker
  - deploy
  - notification

cache:
  paths:
  - node_modules/
  
install_dependencies:
  image: node:latest
  stage: build
  tags:
    - link-keeper-executor
  script:
    - npm install

# lint:
#   image: node:latest
#   stage: lint
#   tags:
#     - link-keeper-executor
#   script:
#     - npm run lint
#   dependencies: 
#     - install_dependencies

# integration_test:
#   services:
#     - mongo:latest
#   image: node:latest
#   stage: test
#   variables:
#     PORT: $PORT
#     LINK_ENCRYPT_KEY: $LINK_ENCRYPT_KEY
#     MONGO_HOST: $MONGO_HOST
#     MONGO_PORT: $MONGO_PORT
#     MONGO_DATABASE_NAME: 'link_keeper_integration_test'
#   tags:
#     - link-keeper-executor
#   script:
#     - npm run test
#   dependencies: 
#     - install_dependencies

# build-docker-image:
#   services:
#     - docker:19.03.0-dind
#   before_script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
#   stage: docker
#   variables:
#     PORT: $PORT
#     LINK_ENCRYPT_KEY: $LINK_ENCRYPT_KEY
#   dependencies: 
#     - install_dependencies
#   tags:
#     - link-keeper-executor
#   script:
#     - docker build -f .docker/Dockerfile -t registry.gitlab.com/marcusbalbi/link-keeper-server .
#     - docker tag registry.gitlab.com/marcusbalbi/link-keeper-server registry.gitlab.com/marcusbalbi/link-keeper-server:latest
#     - docker push registry.gitlab.com/marcusbalbi/link-keeper-server:latest

deploy-local:
  stage: deploy
  tags:
    - link-keeper-executor-deploy
  script:
    - cp .env.example .env
    - tar cfz server.tgz *
    - ssh balbi@172.17.0.1 'mkdir -p projetos/deploy/link-keeper/server'
    - scp server.tgz balbi@172.17.0.1:projetos/deploy/link-keeper/server
    - ssh balbi@172.17.0.1 'cd projetos/deploy/link-keeper/server; tar xfz server.tgz; /usr/bin/docker-compose up -d'
  dependencies: 
    - install_dependencies

# notification-success:
#     stage: notification
#     tags:
#     - link-keeper-executor-deploy
#     when: on_success
#     script:
#     - echo "tudo deu certo"

# notification-failed:
#     stage: notification
#     tags:
#     - link-keeper-executor-deploy
#     when: on_failure
#     script:
#     - echo "deu errado"