image: docker:stable

services:
- docker:dind

before_script:
- docker info

build-docker-backend:
  stage: build
  script:
    - docker build -f .docker/server.dockerfile -t registry.gitlab.com/marcusbalbi/link-keeper .