image: docker:19.03.0

stages:
  - build
  - lint
  - test
  - deploy


install_dependencies:
  image: node:latest
  stage: build
  cache:
    paths:
    - node_modules/
  tags:
    - link-keeper-executor
  script:
    - npm install

lint:
  image: node:latest
  stage: lint
  tags:
    - link-keeper-executor
  script:
    - eslint ./src
  dependencies: 
    - install_dependencies

#build-docker-image:
#  services:
#    - docker:19.03.0-dind
#    - mongo:latest
#  before_script:
#    - docker info
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
#  stage: deploy
#  variables:
#    PORT: $PORT
#    LINK_ENCRYPT_KEY: $LINK_ENCRYPT_KEY
#    MONGO_HOST: $MONGO_HOST
#    MONGO_PORT: $MONGO_PORT
#    MONGO_DATABASE_NAME: $MONGO_DATABASE_NAME
#    MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
#    MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
#  tags:
#    - link-keeper-executor
#  script:
#    - docker build -f .docker/Dockerfile -t registry.gitlab.com/marcusbalbi/link-keeper-server .
#    - docker tag registry.gitlab.com/marcusbalbi/link-keeper-server registry.gitlab.com/marcusbalbi/link-keeper-server:latest
#    - docker push registry.gitlab.com/marcusbalbi/link-keeper-server:latest