image: docker:stable

services:
- docker:dind

before_script:
- docker info
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com

build-docker-backend:
  stage: build
  script:
    - docker build -f .docker/server.dockerfile -t registry.gitlab.com/marcusbalbi/link-keeper .
    - docker tag registry.gitlab.com/marcusbalbi/link-keeper registry.gitlab.com/marcusbalbi/link-keeper:latest
    - docker push registry.gitlab.com/marcusbalbi/link-keeper:latest