version: '3.7'
services:
  mongo:
    image: mongo
    container_name: link_keeper_mongodb
    networks: 
      - link_keeper_network
    env_file:
    - ./.env
    volumes: 
      - "link_keeper_volume:/data/db"
  server:
    image: registry.gitlab.com/marcusbalbi/link-keeper-server
    container_name: link_keeper_server
    networks: 
      - link_keeper_network
    ports:
      - "3008:3009"
    env_file:
    - ./.env
    environment:
      - TZ=America/Sao_Paulo
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - "./:/var/www/app"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on: 
      - mongo
networks:
  link_keeper_network:
    driver: bridge
volumes:
  link_keeper_volume:
    driver: local