version: '3.7'
services:
  mongo:
    image: mongo
    networks: 
      - link_keeper_network
    environment: 
      - MONGO_HOST
      - MONGO_PORT
      - MONGO_DATABASE_NAME
    volumes: 
      - "link_keeper_volume:/data/db"
  server:
    image: registry.gitlab.com/marcusbalbi/link-keeper:latest
    networks: 
      - link_keeper_network
    ports:
      - "3008:3009"
    environment:
      - TZ=America/Sao_Paulo
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on: 
      - mongo
networks:
  link_keeper_network:
    driver: bridge
volumes:
  link_keeper_volume:
    driver: local