version: '3.7'
services:
  server:
    build:
      dockerfile: ./server/Dockerfile
      context: .
    image: marcusbalbi/link_keeper_server
    container_name: link_keeper_server
    networks: 
      - link_keeper_network
    ports:
      - "3008:3009"
    env_file:
    - ./server/.env
    environment:
      - TZ=America/Sao_Paulo
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
networks:
  link_keeper_network:
    driver: bridge