version: '3.7'
services:
  mongo:
    image: mongo
    container_name: link_keeper_mongodb
    networks: 
      - link_keeper_network
    restart: always
    env_file:
    - ./server/.env
  server:
    build:
      dockerfile: ./.docker/server.dockerfile
      context: .
    image: marcusbalbi/link_keeper_server
    container_name: link_keeper_server
    networks: 
      - link_keeper_network
    ports:
      - "3008:3009"
    env_file:
    - ./server/.env
    environment:
      - TZ=America/Sao_Paulo
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - "./server:/var/www/app"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on: 
      - mongo
networks:
  link_keeper_network:
    driver: bridge